### ISSUE TITLE
No unit tests

### ISSUE THREAD

**Issue by davidaramant** [DragonSpit/HPCsharp#2]
Do you mind if I contribute a pull request with a test project?  I think I've spotted a bug in the code, but I realized there's not a great way to prove it since there's no test project...

It would be a .NET Core library using NUnit.

I'm interested in helping out with the project where I can.

**Comment by DragonSpit** [comment]
Hi David,
Sorry it took a while to get back to you. Yes, it would be wonderful if you
could help out!
Yeah, you're right about not having unit testing in this project. I have
fairly extensive unit testing in a private repository, which I have not
open-sourced yet.
But, if you're willing to help out, let's add NUnit based test capabilities
to the solution. Hopefully, that will not affect creating the NuGet package.
I'll take a look at your pull-request.
Thanks for helping out,
-Victor

**Comment by DragonSpit** [comment]
NUnit test project is working, providing a nice starting point for open source unit tests.
